version: '2'

services:

  postgrespro:
    image: kelvich/postgrespro
    environment:
      POSTGRES_DB: 'mydatabase'
      POSTGRES_USER: 'myuser'
      # POSTGRES_PASSWORD: 'mypass'
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data


